server:
  port: 8085


#Dev profile configuration#
---
spring:
  profiles: dev
  
secrets: 
  file-path: file:///C:/etc/config/secrets.yml


#Local profile configuration#
---
spring:
  profiles: local
  
secrets: 
  file-path: classpath:/etc/config/secrets.yml